apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  project: default
  source:
    repoURL: git@github.com:Kibria7533/argo-deployments.git
    targetRevision: HEAD
    path: charts/nginx
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
